-- 3. List the first and last name of all authors, separated by a space, (name the column 'author') and the average star rating of their books (name the column 'average_rating').
-- Round average_rating to 2 decimal places.
-- Order by the average rating, lowest first.
-- (16 rows)
